apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cadastro-app
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: cadastro-app
    app.kubernetes.io/name: cadastro-app
    app.kubernetes.io/part-of: cadastro-app
    app.openshift.io/runtime: java
  name: cadastro-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadastro-app
  template:
    metadata:
      labels:
        app: cadastro-app
    spec:
      containers:
      - name: cadastro-app
        imagePullPolicy: Always
        image: quay.io/farid_ahmad/cadastro-app:latest
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
