apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: cadastro-app
  name: cadastro-app
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: cadastro-app
    weight: 100
